//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirusTask.Resx {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirusTask.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AUTHORIZE.
        /// </summary>
        internal static string resAuthorize {
            get {
                return ResourceManager.GetString("resAuthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bacteria.
        /// </summary>
        internal static string resBacteria {
            get {
                return ResourceManager.GetString("resBacteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ENGLISH.
        /// </summary>
        internal static string resBtnEnglish {
            get {
                return ResourceManager.GetString("resBtnEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RASHA.
        /// </summary>
        internal static string resBtnRasha {
            get {
                return ResourceManager.GetString("resBtnRasha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Darkmode.
        /// </summary>
        internal static string resDarkmode {
            get {
                return ResourceManager.GetString("resDarkmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Year, Mortality.
        /// </summary>
        internal static string resDetailInfo {
            get {
                return ResourceManager.GetString("resDetailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Continent, Country.
        /// </summary>
        internal static string resDetailLocation {
            get {
                return ResourceManager.GetString("resDetailLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fullname: Domain.
        /// </summary>
        internal static string resDetailName {
            get {
                return ResourceManager.GetString("resDetailName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SHOW GALLERY.
        /// </summary>
        internal static string resDetailShow {
            get {
                return ResourceManager.GetString("resDetailShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mortality (more).
        /// </summary>
        internal static string resFilterMortality {
            get {
                return ResourceManager.GetString("resFilterMortality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Year (more).
        /// </summary>
        internal static string resFilterYear {
            get {
                return ResourceManager.GetString("resFilterYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Font.
        /// </summary>
        internal static string resFont {
            get {
                return ResourceManager.GetString("resFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Don&apos;t have an account?.
        /// </summary>
        internal static string resGoRegister {
            get {
                return ResourceManager.GetString("resGoRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LOG OUT.
        /// </summary>
        internal static string resLogout {
            get {
                return ResourceManager.GetString("resLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на REGISTER.
        /// </summary>
        internal static string resRegister {
            get {
                return ResourceManager.GetString("resRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ITEMS.
        /// </summary>
        internal static string resTabItems {
            get {
                return ResourceManager.GetString("resTabItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MAP.
        /// </summary>
        internal static string resTabMap {
            get {
                return ResourceManager.GetString("resTabMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SETTINGS.
        /// </summary>
        internal static string resTabSettings {
            get {
                return ResourceManager.GetString("resTabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на USE FILTERS.
        /// </summary>
        internal static string resUseFilters {
            get {
                return ResourceManager.GetString("resUseFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Continent.
        /// </summary>
        internal static string resValueContinent {
            get {
                return ResourceManager.GetString("resValueContinent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Country.
        /// </summary>
        internal static string resValueCountry {
            get {
                return ResourceManager.GetString("resValueCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Domain.
        /// </summary>
        internal static string resValueDomain {
            get {
                return ResourceManager.GetString("resValueDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fullname.
        /// </summary>
        internal static string resValueFullname {
            get {
                return ResourceManager.GetString("resValueFullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mortality.
        /// </summary>
        internal static string resValueMortality {
            get {
                return ResourceManager.GetString("resValueMortality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        internal static string resValuePassword {
            get {
                return ResourceManager.GetString("resValuePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Videolink.
        /// </summary>
        internal static string resValueVideolink {
            get {
                return ResourceManager.GetString("resValueVideolink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Year.
        /// </summary>
        internal static string resValueYear {
            get {
                return ResourceManager.GetString("resValueYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Virus.
        /// </summary>
        internal static string resVirus {
            get {
                return ResourceManager.GetString("resVirus", resourceCulture);
            }
        }
    }
}
